name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 22f2000108@ds.study.iitm.ac.in
        run: echo "Hello, world!"
